### ISSUE TITLE
texlive-full alternatives

### ISSUE THREAD

**Issue by DerMolly** [livioso/pandoc-travis-setup#1]
I'm using your travis setup and it works great, but it takes ~7min per run.  Mainly because it installs texlive-full.

Did you ever try to use less packages of texlive? texlive-base for example?

**Comment by livioso** [comment]
Thanks for suggestions! :) I don't remember trying it with texlive-base (I don't actively use it myself anymore). Should be simple to try out by replacing texlive-full with texlive-base in `.travis.yml`. Let me know if it works and I'll update it.

**Comment by DerMolly** [comment]
I tried to use base and that didn't work at all. Even with a few extra packages I could not get it to work...
